const archiver = require('archiver');
const repoService = require('./repoService');
const hclParser = require('./hclParser');

async function generate({ provider, modulePath, moduleName, values }, outputStream) {
  const variables = await hclParser.getModuleVariables(provider, modulePath);

  const errors = [];
  for (const v of variables) {
    if (v.required && (values[v.name] === undefined || values[v.name] === '')) {
      errors.push(`Required variable "${v.name}" is missing.`);
    }
  }

  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.pipe(outputStream);

  if (errors.length > 0) {
    archive.append(buildErrorLog(errors, provider, moduleName), { name: 'Error.log' });
    await archive.finalize();
    return;
  }

  archive.append(buildMainTf(provider, modulePath, moduleName, variables, values), { name: 'main.tf' });
  archive.append(buildVersionsTf(provider), { name: 'versions.tf' });
  archive.append(buildReadme(provider, moduleName), { name: 'README.md' });

  await archive.finalize();
}

function buildMainTf(provider, modulePath, moduleName, variables, values) {
  const { source, version } = repoService.getModuleSource(provider, modulePath);
  const id = sanitizeId(moduleName || 'checkpoint_cgns');

  const lines = [
    `module "${id}" {`,
    `  source  = "${source}"`,
    `  version = "${version}"`,
    '',
  ];

  const required = variables.filter((v) => v.required);
  const optional = variables.filter((v) => !v.required);

  if (required.length > 0) {
    lines.push('  # Required variables');
    for (const v of required) {
      lines.push(`  ${v.name} = ${formatValue(values[v.name] ?? '', v.type)}`);
    }
    lines.push('');
  }

  if (optional.length > 0) {
    lines.push('  # Optional variables (defaults shown)');
    for (const v of optional) {
      const val = values[v.name] !== undefined ? values[v.name] : v.default;
      if (val !== undefined && val !== null) {
        lines.push(`  ${v.name} = ${formatValue(String(val), v.type)}`);
      }
    }
    lines.push('');
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}

const PROVIDER_TF_NAMES = {
  aws:     'aws',
  azure:   'azurerm',
  gcp:     'google',
  nutanix: 'nutanix',
  vmware:  'vsphere',
  alibaba: 'alicloud',
};

function buildVersionsTf(provider) {
  const tfProvider = PROVIDER_TF_NAMES[provider.toLowerCase()] || provider.toLowerCase();
  return [
    'terraform {',
    '  required_version = ">= 1.0"',
    '  required_providers {',
    `    ${tfProvider} = {`,
    `      source = "hashicorp/${tfProvider}"`,
    '    }',
    '  }',
    '}',
    '',
  ].join('\n');
}

function buildReadme(provider, moduleName) {
  return [
    `# Terraform Configuration`,
    ``,
    `**Provider:** ${provider.toUpperCase()}  `,
    `**Module:** ${moduleName}`,
    ``,
    `## Usage`,
    ``,
    '```bash',
    `# 1. Initialize Terraform`,
    `terraform init`,
    ``,
    `# 2. Preview changes`,
    `terraform plan`,
    ``,
    `# 3. Apply`,
    `terraform apply`,
    '```',
    ``,
    `> Generated by Check Point CGNS IaC Easy Button`,
  ].join('\n') + '\n';
}

function buildErrorLog(errors, provider, moduleName) {
  const ts = new Date().toISOString();
  return [
    `Check Point CGNS IaC Easy Button — Error Log`,
    `Timestamp : ${ts}`,
    `Provider  : ${provider}`,
    `Module    : ${moduleName}`,
    ``,
    `Validation Errors:`,
    ...errors.map((e, i) => `  ${i + 1}. ${e}`),
    ``,
    `Please fill in all required fields and try again.`,
  ].join('\n') + '\n';
}

function formatValue(val, type) {
  if (val === 'true' || val === 'false') return val;
  if (!isNaN(val) && val !== '' && type === 'number') return val;
  if (type && (type.startsWith('list') || type.startsWith('set'))) {
    return val.startsWith('[') ? val : `["${val}"]`;
  }
  if (type && type.startsWith('map')) {
    return val.startsWith('{') ? val : '{}';
  }
  return `"${val.replace(/"/g, '\\"')}"`;
}

function sanitizeId(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[^a-zA-Z_]/, '_');
}

module.exports = { generate };
